import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  ArrowLeft,
  Code,
  FolderOpen,
  FileCode,
  FileText,
  ChevronRight,
  ChevronDown,
  Download,
  Copy,
  Check,
  Terminal,
} from 'lucide-react';
import * as api from '../services/api';
import type { TaskOutput } from '../shared/types';

interface FileNode {
  name: string;
  type: 'file' | 'folder';
  children?: FileNode[];
  content?: string;
  path?: string;
}

function FileTreeItem({
  node,
  depth,
  selectedFile,
  onSelect,
}: {
  node: FileNode;
  depth: number;
  selectedFile: string;
  onSelect: (node: FileNode) => void;
}) {
  const [expanded, setExpanded] = useState(depth === 0);
  const isSelected = selectedFile === node.name;

  const getFileIcon = (name: string) => {
    if (name.endsWith('.py')) return <FileCode size={13} className="text-[#3572A5]" />;
    if (name.endsWith('.json') || name.endsWith('.yaml')) return <FileCode size={13} className="text-[#f59e0b]" />;
    if (name.endsWith('.md') || name.endsWith('.txt')) return <FileText size={13} className="text-[#6366f1]" />;
    if (name.endsWith('.tex') || name.endsWith('.bib')) return <FileText size={13} className="text-[#10a37f]" />;
    return <FileCode size={13} className="text-[#999]" />;
  };

  return (
    <div>
      <button
        onClick={() => {
          if (node.type === 'folder') setExpanded(!expanded);
          else onSelect(node);
        }}
        className={`w-full flex items-center gap-1.5 px-2 py-1.5 text-xs rounded-lg transition-all ${
          isSelected
            ? 'bg-[#10a37f]/10 text-[#10a37f] font-medium'
            : 'text-[#666] dark:text-[#aaa] hover:bg-[#f4f4f4] dark:hover:bg-[#2a2a3e]'
        }`}
        style={{ paddingLeft: `${depth * 14 + 8}px` }}
      >
        {node.type === 'folder' ? (
          <>
            {expanded ? <ChevronDown size={12} className="text-[#999] shrink-0" /> : <ChevronRight size={12} className="text-[#999] shrink-0" />}
            <FolderOpen size={13} className="text-[#f59e0b] shrink-0" />
          </>
        ) : (
          <>
            <span className="w-3 shrink-0" />
            {getFileIcon(node.name)}
          </>
        )}
        <span className="truncate">{node.name}</span>
      </button>
      {node.type === 'folder' && expanded && node.children && (
        <div>
          {node.children.map((child) => (
            <FileTreeItem
              key={child.name}
              node={child}
              depth={depth + 1}
              selectedFile={selectedFile}
              onSelect={onSelect}
            />
          ))}
        </div>
      )}
    </div>
  );
}

// Mock file tree (will be replaced with real data when API supports it)
const defaultFileTree: FileNode[] = [
  {
    name: 'experiment.py',
    type: 'file',
    content: '# Experiment code generated by AI-Scientist\n# Run: python experiment.py --out_dir=run_0\n\nimport argparse\nimport json\nimport os\nimport numpy as np\nimport time\n\ndef run_experiment(args):\n    """Run the experiment."""\n    results = {}\n    start_time = time.time()\n    np.random.seed(args.seed)\n    \n    # ... experiment logic ...\n    \n    results["accuracy"] = {"means": 0.85, "stds": 0.02}\n    results["runtime"] = {"means": time.time() - start_time, "stds": 0.0}\n    return results\n\nif __name__ == "__main__":\n    parser = argparse.ArgumentParser()\n    parser.add_argument("--out_dir", type=str, default="run_0")\n    parser.add_argument("--seed", type=int, default=42)\n    args = parser.parse_args()\n    os.makedirs(args.out_dir, exist_ok=True)\n    results = run_experiment(args)\n    with open(os.path.join(args.out_dir, "final_info.json"), "w") as f:\n        json.dump(results, f, indent=2)\n    print("Done:", results)',
  },
  {
    name: 'plot.py',
    type: 'file',
    content: '# Plotting script\nimport json\nimport matplotlib.pyplot as plt\n\nlabels = {"run_0": "Baseline"}\n\ndef plot_results():\n    # Load and plot results\n    pass\n\nif __name__ == "__main__":\n    plot_results()',
  },
  { name: 'notes.txt', type: 'file', content: '# Experiment notes\n# Generated by AI-Scientist' },
  { name: 'requirements.txt', type: 'file', content: 'numpy\nmatplotlib\ntorch' },
];

export default function CodeViewer({ taskId }: { taskId: string }) {
  const navigate = useNavigate();
  const [output, setOutput] = useState<TaskOutput | null>(null);
  const [loading, setLoading] = useState(true);
  const [selectedFile, setSelectedFile] = useState<FileNode | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    setLoading(true);
    api.getTaskOutput(taskId)
      .then(setOutput)
      .catch(() => setOutput(null))
      .finally(() => setLoading(false));
  }, [taskId]);

  const handleCopy = () => {
    if (selectedFile?.content) {
      navigator.clipboard.writeText(selectedFile.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-16 animate-fade-in">
        <div className="w-6 h-6 border-2 border-[#10a37f] border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (!output?.code_url) {
    return (
      <div className="animate-fade-in">
        <div className="flex items-center gap-3 mb-6">
          <button onClick={() => navigate(`/task/${taskId}`)} className="flex items-center gap-1.5 text-sm text-[#999] hover:text-[#0d0d0d] dark:hover:text-[#e5e5e5] transition-colors">
            <ArrowLeft size={16} />
            返回任务
          </button>
          <h2 className="text-sm font-medium text-[#0d0d0d] dark:text-[#e5e5e5]">代码仓库</h2>
        </div>
        <div className="text-center py-16">
          <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-[#6366f1]/10 to-[#6366f1]/5 flex items-center justify-center mx-auto mb-4">
            <Code size={28} className="text-[#6366f1]/40" />
          </div>
          <p className="text-sm font-medium text-[#666] dark:text-[#aaa]">代码尚未生成</p>
          <p className="text-xs text-[#999] mt-1.5">完成 M4 代码生成模块后将在此处显示</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full animate-fade-in">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-3">
          <button onClick={() => navigate(`/task/${taskId}`)} className="flex items-center gap-1.5 text-sm text-[#999] hover:text-[#0d0d0d] dark:hover:text-[#e5e5e5] transition-colors">
            <ArrowLeft size={16} />
            返回任务
          </button>
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-[#6366f1] to-[#4f46e5] flex items-center justify-center">
              <Terminal size={14} className="text-white" />
            </div>
            <h2 className="text-sm font-semibold text-[#0d0d0d] dark:text-[#e5e5e5]">代码仓库</h2>
          </div>
        </div>
        <div className="flex items-center gap-1.5">
          {output.code_url && output.code_url !== 'demo' && (
            <a
              href={output.code_url}
              download
              className="flex items-center gap-1.5 px-3.5 py-2 rounded-lg text-xs font-medium text-white bg-[#6366f1] hover:bg-[#4f46e5] transition-colors shadow-sm"
            >
              <Download size={12} />
              下载代码
            </a>
          )}
        </div>
      </div>

      {/* Code editor layout */}
      <div className="flex-1 flex rounded-2xl overflow-hidden border border-[#e5e5e5] dark:border-[#333] shadow-sm">
        {/* File tree */}
        <div className="w-52 bg-[#fafafa] dark:bg-[#1a1a2e] border-r border-[#e5e5e5] dark:border-[#333] overflow-y-auto py-2 px-1">
          <div className="px-2 py-1.5 mb-1">
            <span className="text-[10px] font-semibold text-[#999] uppercase tracking-wider">文件列表</span>
          </div>
          {defaultFileTree.map((node) => (
            <FileTreeItem
              key={node.name}
              node={node}
              depth={0}
              selectedFile={selectedFile?.name || ''}
              onSelect={setSelectedFile}
            />
          ))}
        </div>

        {/* Code content */}
        <div className="flex-1 flex flex-col bg-[#1e1e2e]">
          {selectedFile ? (
            <>
              <div className="flex items-center justify-between px-4 py-2.5 bg-[#191929] border-b border-[#333]">
                <div className="flex items-center gap-2">
                  <FileCode size={13} className="text-[#3572A5]" />
                  <span className="text-xs font-medium text-[#ccc]">{selectedFile.name}</span>
                </div>
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[11px] text-[#888] hover:text-white hover:bg-[#333] transition-colors"
                >
                  {copied ? <Check size={12} className="text-[#10a37f]" /> : <Copy size={12} />}
                  {copied ? '已复制' : '复制代码'}
                </button>
              </div>
              <pre className="flex-1 overflow-auto p-4 text-[13px] leading-6 text-[#d4d4d8] font-mono selection:bg-[#10a37f]/30">
                <code>{selectedFile.content}</code>
              </pre>
            </>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-[#555] gap-3">
              <Code size={32} className="text-[#444]" />
              <span className="text-xs">选择左侧文件查看代码</span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
