import { useEffect, useState } from 'react';
import {
  Code,
  FolderOpen,
  FileCode,
  ChevronRight,
  ChevronDown,
  Download,
  Copy,
  Check,
  ExternalLink,
} from 'lucide-react';
import * as api from '../services/api';
import type { TaskOutput } from '../shared/types';

interface FileNode {
  name: string;
  type: 'file' | 'folder';
  children?: FileNode[];
  content?: string;
  language?: string;
}

// Mock file tree for demo
const mockFileTree: FileNode[] = [
  {
    name: 'src',
    type: 'folder',
    children: [
      { name: 'main.py', type: 'file', language: 'python', content: '# Main entry point\nimport torch\nfrom model import TransformerModel\nfrom train import train_model\n\ndef main():\n    model = TransformerModel()\n    train_model(model)\n\nif __name__ == "__main__":\n    main()' },
      { name: 'model.py', type: 'file', language: 'python', content: '# Model definition\nimport torch.nn as nn\n\nclass TransformerModel(nn.Module):\n    def __init__(self):\n        super().__init__()\n        # Model layers...\n        pass\n\n    def forward(self, x):\n        return x' },
      { name: 'train.py', type: 'file', language: 'python', content: '# Training script\ndef train_model(model):\n    # Training loop\n    pass' },
      { name: 'utils.py', type: 'file', language: 'python', content: '# Utility functions\ndef load_data():\n    pass' },
    ],
  },
  { name: 'requirements.txt', type: 'file', content: 'torch>=2.0\nnumpy\npandas\nmatplotlib' },
  { name: 'README.md', type: 'file', language: 'markdown', content: '# Research Project\n\nGenerated by AI Research Agent' },
];

function FileTreeItem({
  node,
  depth,
  selectedFile,
  onSelect,
}: {
  node: FileNode;
  depth: number;
  selectedFile: string;
  onSelect: (node: FileNode) => void;
}) {
  const [expanded, setExpanded] = useState(depth === 0);

  return (
    <div>
      <button
        onClick={() => {
          if (node.type === 'folder') setExpanded(!expanded);
          else onSelect(node);
        }}
        className={`w-full flex items-center gap-1.5 px-2 py-1 text-xs rounded transition-colors ${
          selectedFile === node.name
            ? 'bg-[#ececec] text-[#0d0d0d]'
            : 'text-[#666] hover:bg-[#f4f4f4]'
        }`}
        style={{ paddingLeft: `${depth * 12 + 8}px` }}
      >
        {node.type === 'folder' ? (
          <>
            {expanded ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
            <FolderOpen size={12} className="text-[#f59e0b]" />
          </>
        ) : (
          <>
            <span className="w-3" />
            <FileCode size={12} className="text-[#6366f1]" />
          </>
        )}
        <span className="truncate">{node.name}</span>
      </button>
      {node.type === 'folder' && expanded && node.children && (
        <div>
          {node.children.map((child) => (
            <FileTreeItem
              key={child.name}
              node={child}
              depth={depth + 1}
              selectedFile={selectedFile}
              onSelect={onSelect}
            />
          ))}
        </div>
      )}
    </div>
  );
}

export default function CodeViewer({ taskId }: { taskId: string }) {
  const [output, setOutput] = useState<TaskOutput | null>(null);
  const [loading, setLoading] = useState(true);
  const [selectedFile, setSelectedFile] = useState<FileNode | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    setLoading(true);
    api.getTaskOutput(taskId)
      .then(setOutput)
      .catch(() => setOutput(null))
      .finally(() => setLoading(false));
  }, [taskId]);

  const handleCopy = () => {
    if (selectedFile?.content) {
      navigator.clipboard.writeText(selectedFile.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-16">
        <div className="w-6 h-6 border-2 border-[#10a37f] border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (!output?.code_url) {
    return (
      <div className="text-center py-16">
        <Code size={48} className="mx-auto mb-4 text-[#d9d9d9]" />
        <p className="text-sm text-[#999]">代码尚未生成</p>
        <p className="text-xs text-[#ccc] mt-1">完成 M4 代码生成模块后将在此处显示</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-[500px]">
      {/* Toolbar */}
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-sm font-medium text-[#0d0d0d]">生成代码</h3>
        <div className="flex items-center gap-1">
          {output.code_url && (
            <a
              href={output.code_url}
              download
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-[#666] bg-[#f4f4f4] hover:bg-[#ececec] transition-colors"
            >
              <Download size={12} />
              下载代码
            </a>
          )}
        </div>
      </div>

      {/* Code editor layout */}
      <div className="flex-1 flex rounded-xl overflow-hidden border border-[#e5e5e5]">
        {/* File tree */}
        <div className="w-48 bg-[#f9f9f9] border-r border-[#e5e5e5] overflow-y-auto py-2">
          {mockFileTree.map((node) => (
            <FileTreeItem
              key={node.name}
              node={node}
              depth={0}
              selectedFile={selectedFile?.name || ''}
              onSelect={setSelectedFile}
            />
          ))}
        </div>

        {/* Code content */}
        <div className="flex-1 flex flex-col bg-[#1e1e1e]">
          {selectedFile ? (
            <>
              <div className="flex items-center justify-between px-4 py-2 bg-[#252526] border-b border-[#333]">
                <span className="text-xs text-gray-400">{selectedFile.name}</span>
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1 px-2 py-1 rounded text-xs text-gray-400 hover:text-gray-200 hover:bg-[#333] transition-colors"
                >
                  {copied ? <Check size={12} /> : <Copy size={12} />}
                  {copied ? '已复制' : '复制'}
                </button>
              </div>
              <pre className="flex-1 overflow-auto p-4 text-xs leading-5 text-gray-300 font-mono">
                <code>{selectedFile.content}</code>
              </pre>
            </>
          ) : (
            <div className="flex-1 flex items-center justify-center text-gray-600 text-xs">
              选择左侧文件查看代码
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
